CFLAGS := -ansi -pedantic-errors
CFLAGS += -Wall -Werror -Wshadow -Wwrite-strings
CC := gcc

all:public01.x public02.x public03.x public04.x public05.x public06.x public07.x public08.x public09.x public10.x

public01.x:public01.o machine.o interpreter.o 
	$(CC) $(CFLAGS)  public01.o machine.o interpreter.o -o public01.x 
public01.o:public01.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public01.c 

public02.x:public02.o machine.o interpreter.o 
	$(CC) $(CFLAGS) public02.o machine.o interpreter.o -o public02.x 
public02.o:public02.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public02.c 

public03.x:public03.o machine.o interpreter.o
	$(CC) $(CFLAGS)  public03.o machine.o interpreter.o -o public03.x 
public03.o:public03.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public03.c 

public04.x:public04.o machine.o interpreter.o
	$(CC) $(CFLAGS)  public04.o machine.o interpreter.o -o public04.x
public04.o:public04.c interpreter.h machine.h
	$(CC) $(CFLAGS) -c public04.c 

public05.x:public05.o machine.o interpreter.o
	$(CC) $(CFLAGS)  public05.o machine.o interpreter.o -o public05.x
public05.o:public05.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public05.c 

public06.x:public06.o machine.o interpreter.o 
	$(CC) $(CFLAGS) public06.o machine.o interpreter.o -o public06.x 
public06.o:public06.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public06.c 

public07.x:public07.o machine.o interpreter.o 
	$(CC) $(CFLAGS)  public07.o machine.o interpreter.o -o public07.x 
public07.o:public07.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public07.c 

public08.x:public08.o machine.o interpreter.o 
	$(CC) $(CFLAGS)  public08.o machine.o interpreter.o -o public08.x 
public08.o:public08.c machine.h interpreter.h
	$(CC) $(CFLAGS) -c public08.c 

public09.x:public09.o machine.o interpreter.o 
	$(CC) $(CFLAGS)  public09.o machine.o interpreter.o -o public09.x 
public09.o:public09.c 
	$(CC) $(CFLAGS) -c public09.c

public10.x:public10.o machine.o interpreter.o 
	$(CC) $(CFLAGS)  public10.o machine.o interpreter.o -o public10.x 
public10.o:public10.c interpreter.h machine.h
	$(CC) $(CFLAGS) -c public10.c 

machine.o:machine.c machine.h 
	$(CC) $(CFLAGS) -c machine.c

interpreter.o:interpreter.c interpreter.h machine.h 
	$(CC) $(CFLAGS) -c interpreter.c 
clean:
	rm machine.o
	rm interpreter.o
	rm public??.o
	rm *.x
