#!/bin/tcsh

# CMSC 216, Fall 2015, Project #7
# Public test 10 (public10)
#
# Tests the third program with a list of numbers, searching for several
# numbers that are in the list.

spim -file prog3.s < public10.input
