#!/bin/tcsh

# CMSC 216, Fall 2015, Project #7
# Public test 9 (public09)
#
# Tests the third program with a list of numbers, searching for another
# number that's elsewhere in the list.

spim -file prog3.s < public09.input
