#!/bin/tcsh

# CMSC 216, Fall 2015, Project #7
# Public test 4 (public04)
#
# Tests the first program with values such that there are no multiples of
# the third number between the first two.

spim -file prog1.s < public04.input
