#!/bin/tcsh

# CMSC 216, Fall 2015, Project #7
# Public test 2 (public02)
#
# Tests the first program with values such that there is one multiple of the
# third number between the first two.

spim -file prog1.s < public02.input
